# Generated by Django 3.0.8 on 2020-11-04 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompanionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='grade',
            field=models.CharField(default='N', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='fac_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CompanionApp.Facultad'),
        ),
    ]
