# Generated by Django 3.0.8 on 2020-11-14 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanionApp', '0002_auto_20201103_2016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Matricula',
        ),
    ]
