# Generated by Django 3.0.8 on 2020-11-14 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompanionApp', '0003_delete_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=5, null=True)),
                ('prof', models.CharField(blank=True, max_length=150, null=True)),
                ('semestre', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('fecha', models.CharField(blank=True, max_length=150)),
                ('grade', models.CharField(default='N', max_length=3)),
                ('salones', models.CharField(blank=True, max_length=100)),
                ('horarios', models.CharField(blank=True, max_length=150)),
                ('dias', models.CharField(blank=True, max_length=100)),
                ('course_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CompanionApp.Curso')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
