# Generated by Django 3.0.8 on 2020-11-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanionApp', '0004_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credits_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='credits_taken',
            field=models.IntegerField(default=0),
        ),
    ]
