# Generated by Django 3.0.8 on 2020-11-14 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanionApp', '0005_auto_20201114_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='credits_score',
        ),
    ]
