# Generated by Django 3.0.8 on 2020-11-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanionApp', '0006_remove_user_credits_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='horarios',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='salones',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
