# Generated by Django 3.0.8 on 2020-11-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanionApp', '0007_auto_20201114_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='dias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
