# Generated by Django 3.0.8 on 2020-11-17 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanionApp', '0008_auto_20201114_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='fecha',
        ),
    ]
