# Generated by Django 3.0.8 on 2020-11-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanionApp', '0009_remove_matricula_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credits_taken_score',
            field=models.IntegerField(default=0),
        ),
    ]
