# Generated by Django 3.0.8 on 2020-12-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanionApp', '0010_user_credits_taken_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='current_year',
            field=models.IntegerField(default=1),
        ),
    ]
