# Generated by Django 3.0.8 on 2020-12-07 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompanionApp', '0011_auto_20201207_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxioSemestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=9)),
                ('creditos', models.IntegerField(default=0)),
                ('section', models.CharField(blank=True, max_length=5, null=True)),
                ('prof', models.CharField(blank=True, max_length=150, null=True)),
                ('hours', models.CharField(blank=True, max_length=150, null=True)),
                ('days', models.CharField(blank=True, max_length=100, null=True)),
                ('rooms', models.CharField(blank=True, max_length=100, null=True)),
                ('course_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CompanionApp.Curso')),
            ],
        ),
    ]
