# Generated by Django 3.0.8 on 2020-12-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanionApp', '0012_proxiosemestre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProxioSemestre',
            new_name='ProximoSemestre',
        ),
    ]
