# Generated by Django 3.0.8 on 2020-12-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanionApp', '0013_auto_20201207_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='code',
            field=models.CharField(max_length=15),
        ),
    ]
