# Generated by Django 3.0.8 on 2020-12-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanionApp', '0014_auto_20201207_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proximosemestre',
            name='code',
            field=models.CharField(max_length=15),
        ),
    ]
